FROM ubuntu:26.04
VOLUME ["/home/judge", "/var/lib/mysql","/var/backups"]
ENV DEBIAN_FRONTEND noninteractive
RUN     apt-get update && apt-get -y upgrade
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        apt-utils
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        libmariadb-dev
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        libmysqlclient-dev
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        libmysql++-dev
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        build-essential
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        g++
RUN     DEBIAN_FRONTEND=noninteractive  apt-get -y install --no-install-recommends        wget
RUN wget -O install.sh http://dl.hustoj.com/install-ubuntu26.04.sh
RUN bash install.sh
