#!/bin/bash
cd /home/judge/
git clone https://gitbub.com/zhblue/hustoj.git git
cd git
git pull .
cd ..
cp /home/judge/src/web/include/db_info.inc.php /home/judge/old.inc.php
cp -r git/trunk/* /home/judge/src/
bash /home/judge/src/install/merge.sh /home/judge/old.inc.php /home/judge/src/web/include/db_info.inc.php

cd /home/judge/src/core
pkill -9 judged
bash make.sh
cd ../install
chmod +x g++.sh gcc.sh makeout.sh
mysql jol< update.sql
judged

web_user=`grep www /etc/passwd|awk -F: '{print $1}'`
mkdir /var/log/hustoj/
chown -R $web_user /var/log/hustoj

chmod 770 /home/judge/src/web/upload
chown $web_user -R /home/judge/src/web/upload

